development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://npnyymvqhgpaey:kOelTMXew7T3Gh4E_uxT94_ute@ec2-54-235-125-38.compute-1.amazonaws.com:5432/dbl3b9bpa5lv8u
